src/java/com/ufpr/tads/sac/beans/PesquisaGerente.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ufpr.tads.sac.beans;

import java.io.Serializable;

/**
 *
 * @author rhone
 */
public class PesquisaGerente implements Serializable {

   private String CampoS1;
   private String CampoS2;
   private int CampoI1;
   private int CampoI2;
   private float CampoF1;
   private float CampoF2;

    public PesquisaGerente() {

    }

    public String getCampoS1() {
        return CampoS1;
    }

    public void setCampoS1(String CampoS1) {
        this.CampoS1 = CampoS1;
    }

    public String getCampoS2() {
        return CampoS2;
    }

    public void setCampoS2(String CampoS2) {
        this.CampoS2 = CampoS2;
    }

    public int getCampoI1() {
        return CampoI1;
    }

    public void setCampoI1(int CampoI1) {
        this.CampoI1 = CampoI1;
    }

    public int getCampoI2() {
        return CampoI2;
    }

    public void setCampoI2(int CampoI2) {
        this.CampoI2 = CampoI2;
    }

    public float getCampoF1() {
        return CampoF1;
    }

    public void setCampoF1(float CampoF1) {
        this.CampoF1 = CampoF1;
    }

    public float getCampoF2() {
        return CampoF2;
    }

    public void setCampoF2(float CampoF2) {
        this.CampoF2 = CampoF2;
    }

}

src/java/com/ufpr/tads/sac/servlet/GerenteServlet.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ufpr.tads.sac.servlet;

import com.ufpr.tads.sac.beans.Cidade;
import com.ufpr.tads.sac.beans.Endereco;
import com.ufpr.tads.sac.beans.Estado;
import com.ufpr.tads.sac.beans.Mensagem;
import com.ufpr.tads.sac.beans.Perfil;
import com.ufpr.tads.sac.beans.Pessoa;
import com.ufpr.tads.sac.facade.AtendimentoFacade;
import com.ufpr.tads.sac.facade.PerfilFacade;
import com.ufpr.tads.sac.facade.PessoaFacade;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

/**
 *
 * @author rhone
 */
@WebServlet(name = "GerenteServlet", urlPatterns = {"/GerenteServlet"})
public class GerenteServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        String action = request.getParameter("action");
        Mensagem msg = new Mensagem();

        HttpSession s = request.getSession(false);
        if (s == null || s.getAttribute("autenticacao") == null) {
            msg.setTitulo("Acesso negado");
            msg.setDescricao("Identifique-se para acessar o sistema!");
            msg.setContexto("danger");
            request.setAttribute("msg", msg);
            RequestDispatcher rd = getServletContext().getRequestDispatcher("/index.jsp");
            rd.forward(request, response);
        }

        if ("listarFunc".equals(action)) {
            Pessoa pessoa = (Pessoa) request.getSession().getAttribute("Func");
            request.setAttribute("listaFunc", PessoaFacade.getAllFunci(pessoa.getId()));
            RequestDispatcher rd = getServletContext().getRequestDispatcher("/modulo/gerente/funcger.jsp");
            rd.forward(request, response);
        }
        if ("show".equals(action)) {
            int idFunc = Integer.parseInt(request.getParameter("id"));
            request.setAttribute("func", PessoaFacade.getFuncGer(idFunc));
            RequestDispatcher rd = getServletContext().getRequestDispatcher("/modulo/gerente/funcgerVisualizar.jsp");
            rd.forward(request, response);
        }
        if ("formUpdate".equals(action)) {
            int idFunc = Integer.parseInt(request.getParameter("id"));
            request.setAttribute("func", PessoaFacade.getFuncGer(idFunc));
            request.setAttribute("perfil", PerfilFacade.getAllPerf());
            request.setAttribute("estados", PessoaFacade.buscarEstados());
            request.setAttribute("estados", PessoaFacade.buscarEstados());
            RequestDispatcher rd = getServletContext().getRequestDispatcher("/modulo/gerente/funcgerAlterar.jsp");
            rd.forward(request, response);
        }
        if ("update".equals(action)) {
            Pessoa psa = new Pessoa();
            Endereco end = new Endereco();
            end.setRua(request.getParameter("rua"));
            String numero = request.getParameter("numero");
            numero = numero.replaceAll("[_]", "");
            numero = numero.replaceAll(" ", "");
            end.setNumero(Integer.parseInt(numero));
            String cepOK = request.getParameter("cep").replaceAll("[.-]", "");
            end.setCep(cepOK);
            end.setComplemento(request.getParameter("complemento"));
            end.setBairro(request.getParameter("bairro"));
            end.setId(Integer.parseInt(request.getParameter("ided")));
            Cidade cid = new Cidade();
            cid.setId(Integer.parseInt(request.getParameter("cidade")));
            Estado est = new Estado();
            est.setId(Integer.parseInt(request.getParameter("estado")));
            cid.setEstado(est);
            end.setCidade(cid);
            psa.setId(Integer.parseInt(request.getParameter("id")));
            Perfil per = new Perfil();
            per.setId(Integer.parseInt(request.getParameter("perfil")));
            String cpf = request.getParameter("cpf");
            String cpfOK = cpf.replaceAll("[.-]", "");
            psa.setCpf(cpfOK);
            psa.setNome(request.getParameter("nome"));
            psa.setEmail(request.getParameter("email"));
            String telefone = request.getParameter("telefone").replaceAll("[()-]", "");
            telefone = telefone.replaceAll(" ", "");
            psa.setTelefone(telefone);
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            String str = request.getParameter("data");
            Date data = null;
            try {
                data = format.parse(str);
            } catch (ParseException e) {
                System.out.println("Erro ao converter data para cadastro do cliente! :(");
            }
            psa.setData(data);
            psa.setEndereco(end);
            psa.setPerfil(per);
            psa.setSenha(request.getParameter("senha"));
            PessoaFacade.Alterar(psa);
            RequestDispatcher rd = getServletContext().getRequestDispatcher("/GerenteServlet?action=listarFunc");
            rd.forward(request, response);
        }

        if ("remove".equals(action)) {
            int idPessoa = Integer.parseInt(request.getParameter("id"));
            PessoaFacade.remover(idPessoa);
            RequestDispatcher rd = getServletContext().getRequestDispatcher("/GerenteServlet?action=listarFunc");
            rd.forward(request, response);
        }

        if ("formNew".equals(action)) {
            request.setAttribute("estados", PessoaFacade.buscarEstados());
            request.setAttribute("perfil", PerfilFacade.getAllPerf());
            request.setAttribute("estados", PessoaFacade.buscarEstados());
            RequestDispatcher rd = getServletContext().getRequestDispatcher("/modulo/gerente/funcgerAlterar.jsp");
            rd.forward(request, response);
        }

        if ("new".equals(action)) {
            Pessoa psa = new Pessoa();
            Endereco end = new Endereco();
            end.setRua(request.getParameter("rua"));
            String numero = request.getParameter("numero");
            numero = numero.replaceAll("[_]", "");
            numero = numero.replaceAll(" ", "");
            end.setNumero(Integer.parseInt(numero));
            String cepOK = request.getParameter("cep").replaceAll("[.-]", "");
            end.setCep(cepOK);
            end.setComplemento(request.getParameter("complemento"));
            end.setBairro(request.getParameter("bairro"));
            Cidade cid = new Cidade();
            cid.setId(Integer.parseInt(request.getParameter("cidade")));
            Estado est = new Estado();
            est.setId(Integer.parseInt(request.getParameter("estado")));
            cid.setEstado(est);
            end.setCidade(cid);
            Perfil per = new Perfil();
            per.setId(Integer.parseInt(request.getParameter("perfil")));
            String cpf = request.getParameter("cpf");
            String cpfOK = cpf.replaceAll("[.-]", "");
            psa.setCpf(cpfOK);
            psa.setNome(request.getParameter("nome"));
            String telefone = request.getParameter("telefone").replaceAll("[()-]", "");
            telefone = telefone.replaceAll(" ", "");
            psa.setTelefone(telefone);
            psa.setEmail(request.getParameter("email"));
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            String str = request.getParameter("data");
            Date data = null;
            try {
                data = format.parse(str);
            } catch (ParseException e) {
                System.out.println("Erro ao converter data para cadastro do cliente! :(");
            }
            psa.setData(data);
            psa.setEndereco(end);
            psa.setPerfil(per);
            psa.setSenha(request.getParameter("senha"));
            PessoaFacade.InserirFunc(psa);
            RequestDispatcher rd = getServletContext().getRequestDispatcher("/GerenteServlet?action=listarFunc");
            rd.forward(request, response);
        }

    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)

web/modulo/gerente/Abertos.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@page errorPage="/erro.jsp" %>

<c:if test="${empty autenticacao}">
    <jsp:useBean id="msg" class="com.ufpr.tads.sac.beans.Mensagem" scope="request"/>
    <c:set target="${msg}" property="titulo" value="Acesso negado"/>
    <c:set target="${msg}" property="descricao" value="Identifique-se para acessar o sistema!"/>
    <c:set target="${msg}" property="contexto" value="danger"/>
    <jsp:forward page="/index.jsp"/>
</c:if>

<!DOCTYPE html>
<html>
    <head>
        <title>Beauty Embuste - SAC</title>
        <meta charset="UTF-8">
        <meta name="author" content="David Cabral & Rhonner Matheus">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="/sac/css/bootstrap.min.css">
        <link rel="stylesheet" href="/sac/css/animate.css">
        <link rel="stylesheet" href="/sac/css/styles.css">
        <link rel="stylesheet" href="/sac/css/dataTables.bootstrap4.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    </head>
    <body>

        <c:if test="${!empty msg}">
            <div class="alert alert-${msg.contexto} alert-dismissible shadow fade show" role="alert">
                <h5>${msg.titulo}</h5>
                ${msg.descricao}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </c:if>

        <section id="gerente">

            <nav class="navbar navbar-expand-lg navbar-light bg-transparent shadow sticky-top mb-3">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler"
                        aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggler">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item dropdown px-4">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-headset"></i> Atendimentos
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="AtendimentoServlet?action=inicial"><i class="fa fa-signature"></i> Dados gerenciais</a>                                
                                <a class="dropdown-item" href="AtendimentoServlet?action=listarAberto"><i class="fa fa-clock"></i> Abertos</a>
                                <a class="dropdown-item" href="AtendimentoServlet?action=listarTudo"><i class="fa fa-list"></i> Todos</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown px-4">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-users"></i> Funcionários/Gerentes
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="GerenteServlet?action=formNew"><i class="fa fa-plus"></i> Novo</a>
                                <a class="dropdown-item" href="GerenteServlet?action=listarFunc"><i class="fa fa-list"></i> Todos</a>
                            </div>
                        </li>
                        <li class="nav-item px-4">
                            <a class="nav-link" href="/sac/modulo/gerente/relats.jsp"><i class="fa fa-file-alt"></i> Relatórios</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <span class="navbar-text px-4">
                            Bem vindo, <b>${autenticacao.nome}</b>
                        </span>
                        <li class="nav-item px-4">
                            <a class="nav-link" href="AutenticacaoServlet?action=logout">Sair <i class="fa fa-sign-out-alt"></i></a>
                        </li>
                    </ul>
                </div>
            </nav>

            <div class="container border border-dark rounded shadow p-5">

                <h3 class="text-center"><i class="fa fa-clock"></i> Atendimentos Abertos</h3>
                <div class="table-responsive-lg">
                    <table class="table table-sm table-bordered table-hover text-center bg-light">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Data/Hora</th>
                                <th scope="col">Descrição</th>
                                <th scope="col">Solução</th>
                                <th scope="col">Situação</th>
                                <th scope="col">Tipo</th>
                                <th scope="col">Produto</th>
                                <th scope="col">Pessoa</th>
                            </tr>
                        </thead>
                        <tbody>
                            <c:forEach items="${lista}" var="list">
                                <c:if test="${list.situacao.id == 1}">
                                    <c:choose>
                                        <c:when test="${list.datahora < timestampp}">
                                            <c:set var="contexto" value="bg-danger"/>
                                        </c:when>
                                        <c:when test="${list.datahora > timestampp}">
                                            <c:set var="contexto" value="bg-warning"/>
                                        </c:when>
                                        <c:otherwise>
                                            <c:set var="contexto" value=""/>
                                        </c:otherwise>
                                    </c:choose>
                                    <tr>
                                        <fmt:formatDate value="${list.datahora}" pattern="dd/MM/yyyy HH:mm:ss" var="data"/>
                                        <td class="${contexto}" scope="row">${list.id}</td>
                                        <td class="${contexto}">${data}</td>
                                        <td class="${contexto}">${list.descricao}</td>
                                        <td class="${contexto}">${list.solucao}</td>
                                        <td class="${contexto}">${list.situacao.nome}</td>
                                        <td class="${contexto}">${list.tipo.nome}</td>
                                        <td class="${contexto}">${list.produto.nome}</td>
                                        <td class="${contexto}">${list.pessoa.nome}</td>
                                    </tr>
                                </c:if>
                            </c:forEach>
                        </tbody>
                    </table>
                </div>
            </div>

        </section>

        <script src="/sac/js/jquery-3.3.1.min.js"></script>
        <script src="/sac/js/popper.min.js"></script>
        <script src="/sac/js/bootstrap.min.js"></script>
        <script src="/sac/js/mensagem.js"></script>
        <script src="/sac/js/jquery.dataTables.min.js"></script>
        <script src="/sac/js/dataTables.bootstrap4.min.js"></script>
        <script src="/sac/js/tabela.js"></script>
    </body>
</html>

web/modulo/gerente/index.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@page errorPage="/erro.jsp" %>

<c:if test="${empty autenticacao}">
    <jsp:useBean id="msg" class="com.ufpr.tads.sac.beans.Mensagem" scope="request"/>
    <c:set target="${msg}" property="titulo" value="Acesso negado"/>
    <c:set target="${msg}" property="descricao" value="Identifique-se para acessar o sistema!"/>
    <c:set target="${msg}" property="contexto" value="danger"/>
    <jsp:forward page="/index.jsp"/>
</c:if>

<!DOCTYPE html>
<html>
    <head>
        <title>Beauty Embuste - SAC</title>
        <meta charset="UTF-8">
        <meta name="author" content="David Cabral & Rhonner Matheus">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="/sac/css/bootstrap.min.css">
        <link rel="stylesheet" href="/sac/css/animate.css">
        <link rel="stylesheet" href="/sac/css/styles.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    </head>
    <body>

        <c:if test="${!empty msg}">
            <div class="alert alert-${msg.contexto} alert-dismissible shadow fade show" role="alert">
                <h5>${msg.titulo}</h5>
                ${msg.descricao}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </c:if>

        <section id="gerente">

            <nav class="navbar navbar-expand-lg navbar-light bg-transparent shadow sticky-top mb-3">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler"
                        aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggler">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item dropdown px-4">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-headset"></i> Atendimentos
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="AtendimentoServlet?action=inicial"><i class="fa fa-signature"></i> Dados gerenciais</a>
                                <a class="dropdown-item" href="AtendimentoServlet?action=listarAberto"><i class="fa fa-clock"></i> Abertos</a>
                                <a class="dropdown-item" href="AtendimentoServlet?action=listarTudo"><i class="fa fa-list"></i> Todos</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown px-4">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-users"></i> Funcionários/Gerentes
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="GerenteServlet?action=formNew"><i class="fa fa-plus"></i> Novo</a>
                                <a class="dropdown-item" href="GerenteServlet?action=listarFunc"><i class="fa fa-list"></i> Todos</a>
                            </div>
                        </li>
                        <li class="nav-item px-4">
                            <a class="nav-link" href="/sac/modulo/gerente/relats.jsp"><i class="fa fa-file-alt"></i> Relatórios</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <span class="navbar-text px-4">
                            Bem vindo, <b>${autenticacao.nome}</b>
                        </span>
                        <li class="nav-item px-4">
                            <a class="nav-link" href="AutenticacaoServlet?action=logout">Sair <i class="fa fa-sign-out-alt"></i></a>
                        </li>
                    </ul>
                </div>
            </nav>

            <div class="container border border-dark rounded shadow p-4">

                <h3 class="text-center"><i class="fa fa-signature"></i> Dados gerenciais</h3>
                <div class="row m-0">

                    <div class="p-2 col-md-6">
                        <div class="border border-dark rounded shadow p-4 text-center">
                            <h5>Quantidade de atendimentos</h5>
                            <h1>${total}</h1>
                        </div>
                    </div>
                    <div class="p-2 col-md-6">
                        <div class="border border-dark rounded shadow p-4 text-center">
                            <h5>Quantidade de atendimentos abertos</h5>
                            <h1>${EmAberto} (${Perc}%)</h1>
                        </div>
                    </div>
                    <div class="p-2 col-md-12">
                        <div class="border border-dark rounded shadow p-4 text-center">
                            <h5>Quantidade de atendimentos por tipo</h5>
                            <table class="table table-sm">
                                <thead>
                                    <tr>
                                        <th scope="col">Tipo de Atendimento</th>
                                        <th scope="col">Quantidade de Atendimentos em Aberto</th>
                                        <th scope="col">Quantidade de Atendimentos totais</th>
                                    </tr>
                                </thead>
                                <tbody>

                                    <c:forEach items="${Tipos}" var="tip">
                                        <tr>                            
                                            <td>${tip.campoS1}</td>
                                            <td>${tip.campoI1}</td>
                                            <td>${tip.campoI2}</td>
                                        </tr>
                                    </c:forEach>
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>

            </div>

        </section>

        <script src="/sac/js/jquery-3.3.1.min.js"></script>
        <script src="/sac/js/popper.min.js"></script>
        <script src="/sac/js/bootstrap.min.js"></script>
        <script src="/sac/js/mensagem.js"></script>
    </body>
</html>